### PR TITLE
[Porting `CMSSW_13_0_X`] Recipe updates for non-amd64 architectures

### PR DESCRIPTION
**Pull request by aandvalenzuela**
Porting https://github.com/iarspider/cms-spack-repo/pull/34 to `CMSSW_13_0_X` except `geant4` and `herwig3` since recipes have diverged.

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
For me `CMSSW_13_0_X` fails concretizing due to a conflict in `xpmem` (https://github.com/iarspider/cms-spack-repo/blob/CMSSW_13_0_X/environments/CMSSW_13_0_X/spack.yaml#L654), so I updated to version `2.6.6-20220308` following the recipe.  Then I get build error for `xrootd`, so I added the checksum in the recipe for the version in env file (https://github.com/iarspider/cms-spack-repo/blob/CMSSW_13_0_X/environments/CMSSW_13_0_X/spack.yaml#L656), but then it fails in building `llvm`. Not sure if those are the appropriate changes...

**Comment by iarspider** [comment]
Can you post the error you get with llvm?

**Comment by iarspider** [comment]
just in case, look also under `cleanup-cms-repo` branch - maybe merging didn't work properly

**Comment by aandvalenzuela** [comment]
> Can you post the error you get with llvm?

I cannot reproduce the `llvm` error anymore... Nevertheless, it now fails in `clhep`. Should it be `clhep@2.4.5.1+cms` in the env file https://github.com/iarspider/cms-spack-repo/blob/CMSSW_13_0_X/environments/CMSSW_13_0_X/spack.yaml#L153, right?

**Comment by iarspider** [comment]
@aandvalenzuela probably yes. The general rule is - if, in our recipe (i.e.  the one in `repos/cms/packages`), we override `git` attribute, then version must end in `.cms`. Otherwise, the version remains the same, but `cms` variant should be enabled (although it should be already enabled for all packages that have it - https://github.com/iarspider/cms-spack-repo/blob/CMSSW_13_0_X/environments/CMSSW_13_0_X/spack.yaml#L18)

**Comment by aandvalenzuela** [comment]
I managed to reproduce again the `llvm` error. I have opened https://github.com/iarspider/cms-spack-repo/issues/36 so that we can track the changes required to build environment `CMSSW_13_0_X` (and not to forget them specially after the break).

**Comment by iarspider** [comment]
@aandvalenzuela can I merge this?

**Comment by aandvalenzuela** [comment]
I think so, it is only the changes for `geant4` and `herwig3` missing since recipes have diverged. The rest is identical to https://github.com/iarspider/cms-spack-repo/pull/34.

**Pull request merged**
